import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RobotServerProvider } from "@/hooks/use-robot-server";
import "./globals.css";
import { ConnectToServer } from "@/components/connect-to-server";
import { Navigation } from "@/components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <RobotServerProvider>
          <ConnectToServer />
          {children}
        </RobotServerProvider>
      </body>
    </html>
  );
}
